--[[                                                                           ]]--
--[[  Generated by FAF Map Editor                                              ]]--
--[[                                                                           ]]--
--[[                                                                           ]]--
--[[  Scenario                                                                 ]]--
--[[                                                                           ]]--
Scenario = {
    next_area_id = '0',
    --[[                                                                           ]]--
    --[[  Props                                                                    ]]--
    --[[                                                                           ]]--
    Props = {
    },
    --[[                                                                           ]]--
    --[[  Areas                                                                    ]]--
    --[[                                                                           ]]--
    Areas = {
        ['M1_Playable_Area'] = {
            ['rectangle'] = RECTANGLE( 128, 600, 650, 896 ),
        },
    },
    --[[                                                                           ]]--
    --[[  Markers                                                                  ]]--
    --[[                                                                           ]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {
                ['M1_UEFAlly_Interceptor_Patrol_A_02'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 444.5, 52.00317, 809.5001 ),
                },
                ['UEFAlly'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 459.5, 52.00317, 844.5001 ),
                },
                ['Mass 00'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 426.5, 52.00317, 856.5 ),
                },
                ['Mass 08'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 259.5, 51.99928, 847.5 ),
                },
                ['Mass 07'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 333.5, 51.99928, 775.5 ),
                },
                ['M1_UEFAlly_Interceptor_Patrol_A_03'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 392.5, 52.00317, 867.5 ),
                },
                ['M1_UEFAlly_Attack_East_A_02'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 585.5, 52.00317, 776.5 ),
                },
                ['M1_UEFAlly_Attack_East_A_01'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 523.5, 50.01477, 866.5 ),
                },
                ['Hydrocarbon 01'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 443.5, 52.00317, 789.5001 ),
                },
                ['M1_UEFAlly_Attack_East_A_03'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 610.5, 54.35488, 673.5001 ),
                },
                ['M1_UEFAlly_Interceptor_Patrol_A_01'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 495.5, 52.00317, 863.5001 ),
                },
                ['Mass 05'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 368.5, 52.00317, 771.5 ),
                },
                ['Mass 02'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 503.5, 52.00317, 855.5 ),
                },
                ['M1_South_Base_Marker'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 447.5, 52.00317, 835.5 ),
                },
                ['Mass 10'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 392.5, 52.00317, 843.5001 ),
                },
                ['Mass 06'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 361.5, 52.00317, 737.5 ),
                },
                ['Mass 01'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 448.5, 52.00317, 880.5 ),
                },
                ['M1_UEFAlly_Attack_East_B_03'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 605.5, 52.96807, 656.5 ),
                },
                ['Mass 03'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 406.5, 52.00317, 720.5 ),
                },
                ['Hydrocarbon 02'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 225.5, 52.00317, 853.5001 ),
                },
                ['Mass 04'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 421.5, 52.00317, 732.5 ),
                },
                ['Player1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 390.5, 52.00317, 750.5 ),
                },
                ['M1_UEFAlly_Land_Patrol_A_01'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 461.5, 52.00317, 787.5 ),
                },
                ['M1_UEFAlly_Attack_East_B_01'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 456.5, 52.00317, 795.5 ),
                },
                ['Mass 09'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 191.5, 52.00317, 787.5 ),
                },
                ['M1_UEFAlly_Land_Patrol_A_02'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 497.5, 51.76487, 822.5 ),
                },
                ['M1_UEFAlly_Land_Patrol_A_03'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 510.5, 52.00317, 866.5 ),
                },
                ['M1_UEFAlly_Attack_East_B_02'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 511.5, 50.00305, 723.5001 ),
                },
                ['Hydrocarbon 00'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 458.5, 52.00317, 806.5 ),
                },
                ['M1_UEFAlly_Interceptor_Patrol_B_01'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 356.5, 50.31557, 872.5 ),
                },
                ['M1_UEFAlly_Interceptor_Patrol_B_02'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 353.5, 52.00317, 759.5001 ),
                },
                ['M1_UEFAlly_Interceptor_Patrol_B_03'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 434.5, 51.93285, 740.5 ),
                },
                ['M1_UEFAlly_Interceptor_Patrol_B_04'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 511.5, 51.99927, 851.5 ),
                },
            },
        },
    },
    Chains = {
        ['M1_UEFAlly_Attack_East_A'] = {
            Markers = {
                "M1_UEFAlly_Attack_East_A_01",
                "M1_UEFAlly_Attack_East_A_02",
                "M1_UEFAlly_Attack_East_A_03",
            },
        },
        ['M1_UEFAlly_Attack_East_B'] = {
            Markers = {
                "M1_UEFAlly_Attack_East_B_01",
                "M1_UEFAlly_Attack_East_B_02",
                "M1_UEFAlly_Attack_East_B_03",
            },
        },
        ['M1_UEFAlly_Interceptor_Patrol_A'] = {
            Markers = {
                "M1_UEFAlly_Interceptor_Patrol_A_01",
                "M1_UEFAlly_Interceptor_Patrol_A_02",
                "M1_UEFAlly_Interceptor_Patrol_A_03",
            },
        },
        ['M1_UEFAlly_Land_Patrol_A'] = {
            Markers = {
                "M1_UEFAlly_Land_Patrol_A_01",
                "M1_UEFAlly_Land_Patrol_A_02",
                "M1_UEFAlly_Land_Patrol_A_03",
            },
        },
        ['M1_UEFAlly_Interceptor_Patrol_B'] = {
            Markers = {
                "M1_UEFAlly_Interceptor_Patrol_B_01",
                "M1_UEFAlly_Interceptor_Patrol_B_02",
                "M1_UEFAlly_Interceptor_Patrol_B_03",
                "M1_UEFAlly_Interceptor_Patrol_B_04",
            },
        },
    },
    next_queue_id = '0',
    --[[                                                                           ]]--
    --[[  Orders                                                                   ]]--
    --[[                                                                           ]]--
    Orders = {
    },
    next_platoon_id = '0',
    --[[                                                                           ]]--
    --[[  Platoons                                                                 ]]--
    --[[                                                                           ]]--
    Platoons = {
    },
    next_army_id = '0',
    next_group_id = '0',
    next_unit_id = '0',
    --[[                                                                           ]]--
    --[[  Armies                                                                   ]]--
    --[[                                                                           ]]--
    Armies = {
        --[[                                                                           ]]--
        --[[  Player1                                                                  ]]--
        --[[                                                                           ]]--
        ['Player1'] = 
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['Commander'] = {
                        type = 'uel0001',
                        orders = '',
                        platoon = '',
                        Position = { 376.5, 52.00317, 765.5 },
                        Orientation = { 0, -3.836294, 0 },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  UEFAlly                                                                  ]]--
        --[[                                                                           ]]--
        ['UEFAlly'] = 
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['M1_Land_Platoon_A'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['UNIT_38'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 464.5, 52.00317, 836.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_43'] = {
                                type = 'uel0101',
                                orders = '',
                                platoon = '',
                                Position = { 468.5, 52.00317, 838.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_37'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 462.5, 52.00317, 836.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_34'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 464.5, 52.00317, 834.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_42'] = {
                                type = 'uel0101',
                                orders = '',
                                platoon = '',
                                Position = { 468.5, 52.00317, 836.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_40'] = {
                                type = 'uel0101',
                                orders = '',
                                platoon = '',
                                Position = { 460.5, 52.00317, 836.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_45'] = {
                                type = 'uel0104',
                                orders = '',
                                platoon = '',
                                Position = { 464.5, 52.00317, 838.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_32'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 460.5, 52.00317, 834.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_33'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 462.5, 52.00317, 834.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_41'] = {
                                type = 'uel0101',
                                orders = '',
                                platoon = '',
                                Position = { 460.5, 52.00317, 838.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_46'] = {
                                type = 'uel0104',
                                orders = '',
                                platoon = '',
                                Position = { 466.5, 52.00317, 838.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_35'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 466.5, 52.00317, 834.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_36'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 468.5, 52.00317, 834.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_44'] = {
                                type = 'uel0104',
                                orders = '',
                                platoon = '',
                                Position = { 462.5, 52.00317, 838.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_39'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 466.5, 52.00317, 836.5 },
                                Orientation = { 0, 0, 0 },
                            },
                        },
                    },
                    ['M1_South_Base_D1'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['M1_South_Base_D2'] = GROUP {
                                orders = '',
                                platoon = '',
                                Units = {
                                    ['M1_South_Base_D3'] = GROUP {
                                        orders = '',
                                        platoon = '',
                                        Units = {
                                            ['UNIT_5'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 418.5, 52.00317, 848.5001 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_12'] = {
                                                type = 'ueb1103',
                                                orders = '',
                                                platoon = '',
                                                Position = { 503.5, 52.00317, 855.5 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_2'] = {
                                                type = 'ueb1201',
                                                orders = '',
                                                platoon = '',
                                                Position = { 422.5, 52.00317, 860.5 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_16'] = {
                                                type = 'ueb2204',
                                                orders = '',
                                                platoon = '',
                                                Position = { 401.5, 52.00317, 873.5001 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_9'] = {
                                                type = 'ueb1102',
                                                orders = '',
                                                platoon = '',
                                                Position = { 458.5, 52.00317, 806.5 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_11'] = {
                                                type = 'ueb1202',
                                                orders = '',
                                                platoon = '',
                                                Position = { 448.5, 52.00317, 880.5 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_4'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 434.5, 52.00317, 860.5 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_8'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 416.5, 52.00317, 856.5 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_10'] = {
                                                type = 'ueb1202',
                                                orders = '',
                                                platoon = '',
                                                Position = { 426.5, 52.00317, 856.5 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_6'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 420.5, 52.00317, 848.5001 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_1'] = {
                                                type = 'ueb0102',
                                                orders = '',
                                                platoon = '',
                                                Position = { 429.5, 52.00317, 861.5 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_3'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 434.5, 52.00317, 858.5001 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_24'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 422.5, 52.00317, 880.5 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_13'] = {
                                                type = 'ueb1103',
                                                orders = '',
                                                platoon = '',
                                                Position = { 392.5, 52.00317, 843.5001 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_22'] = {
                                                type = 'ueb1105',
                                                orders = '',
                                                platoon = '',
                                                Position = { 420.5, 52.00317, 880.5 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_0'] = {
                                                type = 'ueb0102',
                                                orders = '',
                                                platoon = '',
                                                Position = { 421.5, 52.00317, 853.5001 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_15'] = {
                                                type = 'ueb2104',
                                                orders = '',
                                                platoon = '',
                                                Position = { 480.5, 52.00317, 864.5001 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_23'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 420.5, 52.00317, 878.5001 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_14'] = {
                                                type = 'ueb0102',
                                                orders = '',
                                                platoon = '',
                                                Position = { 465.5, 52.00317, 806.5 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_25'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 420.5, 52.00317, 882.5 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_7'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 416.5, 52.00317, 854.5001 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                        },
                                    },
                                    ['UNIT_19'] = {
                                        type = 'ueb3101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 440.5, 52.00317, 822.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_20'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 440.5, 52.00317, 820.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_21'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 438.5, 52.00317, 822.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_18'] = {
                                        type = 'ueb1102',
                                        orders = '',
                                        platoon = '',
                                        Position = { 443.5, 52.00317, 789.5001 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_17'] = {
                                        type = 'ueb0102',
                                        orders = '',
                                        platoon = '',
                                        Position = { 443.5, 52.00317, 797.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_26'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 466.5, 52.00317, 786.5 },
                                        Orientation = { 0, -3.141593, 0 },
                                    },
                                },
                            },
                            ['UNIT_28'] = {
                                type = 'ueb0102',
                                orders = '',
                                platoon = '',
                                Position = { 463.5, 52.00317, 877.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_31'] = {
                                type = 'ueb2204',
                                orders = '',
                                platoon = '',
                                Position = { 494.5, 52.00317, 886.5 },
                                Orientation = { 0, -3.141593, 0 },
                            },
                            ['UNIT_29'] = {
                                type = 'ueb1201',
                                orders = '',
                                platoon = '',
                                Position = { 465.5, 52.00317, 869.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_27'] = {
                                type = 'ueb0102',
                                orders = '',
                                platoon = '',
                                Position = { 473.5, 52.00317, 867.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_30'] = {
                                type = 'ueb2301',
                                orders = '',
                                platoon = '',
                                Position = { 472.5, 52.00317, 876.5 },
                                Orientation = { 0, -3.141593, 0 },
                            },
                        },
                    },
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                    ['M1_Bomber_Platoon_A'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['UNIT_62'] = {
                                type = 'uea0103',
                                orders = '',
                                platoon = '',
                                Position = { 440.5, 52.00317, 864.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_64'] = {
                                type = 'uea0103',
                                orders = '',
                                platoon = '',
                                Position = { 444.5, 52.00317, 864.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_63'] = {
                                type = 'uea0103',
                                orders = '',
                                platoon = '',
                                Position = { 442.5, 52.00317, 864.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_65'] = {
                                type = 'uea0103',
                                orders = '',
                                platoon = '',
                                Position = { 446.5, 52.00317, 864.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                        },
                    },
                    ['M1_Land_Platoon_B'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['UNIT_48'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 412.5, 52.00317, 834.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_56'] = {
                                type = 'uel0101',
                                orders = '',
                                platoon = '',
                                Position = { 410.5, 52.00317, 838.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_52'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 412.5, 52.00317, 836.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_54'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 416.5, 52.00317, 836.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_61'] = {
                                type = 'uel0104',
                                orders = '',
                                platoon = '',
                                Position = { 416.5, 52.00317, 838.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_49'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 414.5, 52.00317, 834.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_55'] = {
                                type = 'uel0101',
                                orders = '',
                                platoon = '',
                                Position = { 410.5, 52.00317, 836.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_51'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 418.5, 52.00317, 834.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_60'] = {
                                type = 'uel0104',
                                orders = '',
                                platoon = '',
                                Position = { 414.5, 52.00317, 838.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_57'] = {
                                type = 'uel0101',
                                orders = '',
                                platoon = '',
                                Position = { 418.5, 52.00317, 836.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_53'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 414.5, 52.00317, 836.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_58'] = {
                                type = 'uel0101',
                                orders = '',
                                platoon = '',
                                Position = { 418.5, 52.00317, 838.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_59'] = {
                                type = 'uel0104',
                                orders = '',
                                platoon = '',
                                Position = { 412.5, 52.00317, 838.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_50'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 416.5, 52.00317, 834.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_47'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 410.5, 52.00317, 834.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                        },
                    },
                    ['M1_Interceptor_Platoon_A'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['UNIT_67'] = {
                                type = 'uea0102',
                                orders = '',
                                platoon = '',
                                Position = { 378.5, 52.00317, 818.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_68'] = {
                                type = 'uea0102',
                                orders = '',
                                platoon = '',
                                Position = { 356.5, 52.00317, 787.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_71'] = {
                                type = 'uea0102',
                                orders = '',
                                platoon = '',
                                Position = { 409.5, 52.00317, 801.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_76'] = {
                                type = 'uea0102',
                                orders = '',
                                platoon = '',
                                Position = { 457.5, 52.00317, 819.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_69'] = {
                                type = 'uea0102',
                                orders = '',
                                platoon = '',
                                Position = { 380.5, 52.00317, 818.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_66'] = {
                                type = 'uea0102',
                                orders = '',
                                platoon = '',
                                Position = { 354.5, 52.00317, 787.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_73'] = {
                                type = 'uea0102',
                                orders = '',
                                platoon = '',
                                Position = { 422.5, 52.00317, 768.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_70'] = {
                                type = 'uea0102',
                                orders = '',
                                platoon = '',
                                Position = { 420.5, 52.00317, 768.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_75'] = {
                                type = 'uea0102',
                                orders = '',
                                platoon = '',
                                Position = { 457.5, 52.00317, 817.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_74'] = {
                                type = 'uea0102',
                                orders = '',
                                platoon = '',
                                Position = { 411.5, 52.00317, 801.5 },
                                Orientation = { 0, 0, 0 },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  UEFEnemy                                                                 ]]--
        --[[                                                                           ]]--
        ['UEFEnemy'] = 
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  ARMY_17                                                                  ]]--
        --[[                                                                           ]]--
        ['ARMY_17'] = 
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  NEUTRAL_CIVILIAN                                                         ]]--
        --[[                                                                           ]]--
        ['NEUTRAL_CIVILIAN'] = 
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
    },
}
